### ISSUE TITLE
[Bug] Bookmark Sync Issue

### ISSUE THREAD

**Issue by jbhul** [kyxap/koreader-calibre-plugin#91]
> Also on Linux, USB mounted Android reader device, with new version of the plugin trying to sync crashed Calibre with the following log trace. I had to SKIP some filenames, do let me know if the log is sufficient:
> 
> ````
> DEBUG:   85.1 koreader:action:KoreaderAction:sync_to_calibre:Trying to get sidecar from <calibre.devices.folder_device.driver.FOLDER_DEVICE object at 0x7f8c1e5ce380>, with sidecar_path: /run/user/1000/gvfs/mtp:host=rockchip_Supernote_A5_X_SN100B20012692/Supernote/INBOX/books/SKIP.sdr/metadata.epub.lua
> DeviceJob: metadata_downloaded: Starting set_books_in_library
> DeviceJob: set_books_in_library: books to process= 128
> Job: 2 Get list of books on device finished
> No details available.
> DEBUG:   85.1 koreader:action:KoreaderAction:get_sidecar:Parsing: /run/user/1000/gvfs/mtp:host=rockchip_Supernote_A5_X_SN100B20012692/Supernote/INBOX/books/SKIP.sdr/metadata.epub.lua
> DEBUG:   85.2 koreader:action:KoreaderAction:sync_to_calibre:sidecar_contents
> DeviceJob: set_books_in_library finished: time= 0.1802978515625
> DeviceJob: metadata_downloaded: updating views
> DeviceJob: metadata_downloaded: syncing
> DeviceJob: metadata_downloaded: refreshing ondevice
> DeviceJob: metadata_downloaded: sending metadata_available signal
> DeviceJob: 2 Get list of books on device callback returned
> DEBUG:   85.6 koreader:action:KoreaderAction:sync_to_calibre:sidecar_contents is found!
> DEBUG:   85.6 koreader:action:KoreaderAction:sync_to_calibre:transforming value for #current_percent_read
> DEBUG:   85.6 koreader:action:KoreaderAction:sync_to_calibre:transforming value for #current_percent_read_integer
> DEBUG:   85.6 koreader:action:KoreaderAction:sync_to_calibre:subproperty "rating" not found in value
> DEBUG:   85.6 koreader:action:KoreaderAction:sync_to_calibre:transforming value for #bookmarks_and_highlights
> QObject::setParent: Cannot set parent, new parent is in a different thread
> Segmentation fault

> In my case unchecking the "Bookmarks column" in sync settings allowed plugin to run without error. The custom database column created for this field sync was Long text with Interpret this column as set to Plain text formatted using markdown - just exactly as in setup instructions on the plugin GitHub page.
>
>PS: I guess I should move this bug report into separate ticket? The only relevance with earlier bug report in the current ticket is the new version of the plugin?

 _Originally posted by @sokolgeo in [#88](https://github.com/harmtemolder/koreader-calibre-plugin/issues/88#issuecomment-2848624077)_

This was getting confusing and this is a completely separate bug than what is referenced in the other issue.

@sokolgeo Please confirm the following
1. Is this a new install/setup or was this working before you updated the plugin. Basically is this a bug related to the major plugin update or is this just a bug.
2. Does this occur on a specific book? As in does the progress bar progress over some books before arriving at this issue? If so which book? Can you include a copy of that sidecar?
Also note that brotli was never a relevant issue for you and your use case, you had a completely separate issue.

@kyxap This issue, based on the log, seems to be from the clean_bookmarks code in init which was untouched. Not too sure if this is just a issue with a specific sidecar but comparing the sidecar that causes the issue with one that works will likely help id the issue, because it works for me and this seems to be the only report of an issue with the bookmarks column syncing. 
Frankly not too sure where `Cannot set parent, new parent is in a different thread` comes from.

**Comment by sokolgeo** [comment]
@jbhul 
1. Before updating the plugin I had different error and could not use the plugin for its main (for me)  functionality - syncing highlights and bookmarks. So I'd call this bug as related to plugin update, because for me it started appearing with new version of the plugin only.
2. I shared the logs in #88, don't have access  to more logs at the moment. I believe the actual cause was already found in #88 and fix merged in #90

**Comment by kyxap** [comment]
ok lets wait for new release and try to reproduce it

**Comment by jbhul** [comment]
@sokolgeo 
> 1. Before updating the plugin I had different error and could not use the plugin for its main (for me)  functionality - syncing highlights and bookmarks. So I'd call this bug as related to plugin update, because for me it started appearing with new version of the plugin only.

So it wasn't working for syncing bookmarks before but now it still doesn't work but with a different error?

> 2. I shared the logs in [[Bug] Recent update breaks plugin #88](https://github.com/harmtemolder/koreader-calibre-plugin/issues/88), don't have access  to more logs at the moment. I believe the actual cause was already found in [[Bug] Recent update breaks plugin #88](https://github.com/harmtemolder/koreader-calibre-plugin/issues/88) and fix merged in [Remove brotli dependency #90](https://github.com/harmtemolder/koreader-calibre-plugin/pull/90)

I strongly believe Brotli was unrelated to your issue, it got confusing because you talked about this issue in the thread for another issue. The log isn't descriptive enough to really figure out the problem, it's likely an issue with a particular sidecar (maybe an old book or something where the sidecar format changed or some quirk with a bookmark/highlight that's causing problems) which is why I asked for the specific book and sidecar.

Like @kyxap said let's see if it is still broken in the new version and then follow up.

**Comment by kyxap** [comment]
@sokolgeo @jbhul  are we good to close this one? there anything that we need to look into ? thanks

**Comment by sokolgeo** [comment]
@kyxap yes, please, fine with me to close this ticket.
